theme: jekyll-theme-cayman
title: PyEst | Software Estatístico Desenvolvido em Python
description: Alcides Fonseca, Rick Kazman and Patricia Lago
social-network-links:
  rss: true
  email: "jacksonenazus@gmail.com"
avatar: "icon.png"
